# Generated by Django 5.0.6 on 2024-05-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
    ]
